services:
  stream-app:
    image: link:deploy
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.stream
    volumes:
      - ./data_stream/db:/app/db
    depends_on:
      - api-app
    working_dir: /app
    entrypoint: ["./stream-app"]
    command:
      [
        "0x000359843a543ee2fe414dc14c7e7920ef10f4372990b79d6361cdc0dd1ba782",
        "0x00037da06d56d083fe599397a4769a042d63aa73dc4ef57709d31e9971a5b439",
        "0x0003d338ea2ac3be9e026033b1aa601673c37bab5e13851c59966f9f820754d6"
      ]

  api-app:
    image: linkapi:deploy
    build:
      context: ./py-api-app
      dockerfile: Dockerfile
    container_name: py-api-app
    ports:
      - "8000:8000"
    volumes:
      - ./data_stream/db:/app/db
    restart: always
